import Head from "next/head";
import Chat from "@/components/chat";

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Chat api="/api/chat/systemprompt" />
      </div>
    </>
  );
}
